---
# tasks file for mariadb
- name: Install 'mariadb-server' and 'MySQL-python' packages
  yum: 
    name: "{{ item }}" 
    update_cache: true
    state: latest
  loop:
    - mariadb-server
    - MySQL-python

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

# .my.cnf на VM права root:root
- name: CopyinVM .my.cnf
  copy:
    src: .my.cnf 
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644

- name: Create db wordpr
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    login_password: "{{ password1 }}"
    login_host: localhost
    state: present

- name: create wpuser
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL" 
    login_user: root
    login_password: "{{ password1 }}"
    login_host: localhost
    state: present
  no_log: true

- name: Removes all anonymous user
  mysql_user:
    name: ''
    login_user: root
    login_password: "{{ password1 }}"
    login_host: localhost
    host_all: yes
    state: absent
  no_log: true  

